# Generated by Django 4.2.1 on 2023-05-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_management_app', '0001_initial'),
        ('versioning_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=6)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versioning_management_app.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300, null=True)),
                ('color', models.CharField(max_length=30)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versioning_management_app.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=6)),
                ('assignees', models.ManyToManyField(null=True, related_name='assignees', to='users_management_app.user')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='users_management_app.user')),
                ('labels', models.ManyToManyField(null=True, to='project_management_app.label')),
                ('milestone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management_app.milestone')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versioning_management_app.repository')),
            ],
        ),
    ]
