# Generated by Django 4.2.1 on 2023-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioning_management_app', '0002_branch_repository_collaborators_and_more'),
        ('project_management_app', '0002_remove_issue_created_on_issue_created_at_pullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='base_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_branch', to='versioning_management_app.branch'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='compare_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_branch', to='versioning_management_app.branch'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='issues',
            field=models.ManyToManyField(null=True, to='project_management_app.issue'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='labels',
            field=models.ManyToManyField(null=True, to='project_management_app.label'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management_app.milestone'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versioning_management_app.repository'),
        ),
    ]
