# Generated by Django 4.2 on 2023-05-24 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0003_pullrequest_base_branch_pullrequest_compare_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
