# Generated by Django 4.2.1 on 2023-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_management_app', '0001_initial'),
        ('project_management_app', '0002_remove_issue_created_on_issue_created_at_pullrequest'),
        ('versioning_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=300, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='users_management_app.user')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management_app.issue')),
                ('pull_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management_app.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKE', 'Like'), ('Love', 'Love'), ('HAPPY', 'Happy')], max_length=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_author', to='users_management_app.user')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_actions_management_app.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FORK', 'Fork'), ('STAR', 'Star')], max_length=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_author', to='users_management_app.user')),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repo_action', to='versioning_management_app.repository')),
            ],
        ),
    ]
