# Generated by Django 4.2 on 2023-05-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versioning_management_app', '0002_branch_repository_collaborators_and_more'),
        ('user_actions_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='forked_repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forked_repo', to='versioning_management_app.repository'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('FORK', 'Fork'), ('STAR', 'Star'), ('WATCH', 'Watch')], max_length=6),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('Love', 'Love'), ('HAPPY', 'Happy'), ('SAD', 'Sad')], max_length=10),
        ),
    ]
