# Generated by Django 4.2 on 2023-06-09 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versioning_management_app', '0002_branch_repository_collaborators_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('repository', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('owner', 'name')},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='collaborators',
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('ADMIN', 'Admin')], max_length=50, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versioning_management_app.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'repository')},
            },
        ),
    ]
