# Generated by Django 4.2 on 2023-06-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versioning_management_app', '0004_repository_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='role',
            field=models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('ADMIN', 'Admin')], default='READ', max_length=50),
        ),
    ]
