name: Our GitHub App Test

on: 
  pull_request:
    branches:
    - develop
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./uks_project/
    
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies 
        run: |
         python -m pip install -- upgrade pip
         pip install -r requirements.txt
      
      - name: Test App Code
        run: |
          python project_management_app/tests.py
          python user_actions_management_app/tests.py
          python users_management_app/tests.py
          python versioning_management_app/tests.py